# Generated by Django 3.1 on 2023-10-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20231021_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='extra_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
