# Generated by Django 3.1 on 2023-10-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20231021_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size'), ('pack', 'pack'), ('switchtype', 'switchtype'), ('mounting_option', 'mounting_option')], max_length=100),
        ),
    ]
