# Generated by Django 3.1 on 2023-11-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20231111_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvideo',
            name='video',
            field=models.FileField(upload_to='store/products'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size'), ('pack', 'pack'), ('switchtype', 'switchtype'), ('mounting_option', 'mounting_option'), ('individual_color', 'individual_color'), ('shape', 'shape'), ('batteries_type', 'batteries_type'), ('set', 'set'), ('shelf_size', 'shelf_size'), ('container_type', 'container_type'), ('holder_size', 'holder_size'), ('first_color', 'first_color'), ('second_color', 'secondary_color'), ('third_color', 'third_color'), ('fourth_color', 'fourth_color'), ('type_placement', 'type_placement'), ('cage_color', 'cage_color'), ('seat_color', 'seat_color'), ('stand_type', 'stand_type'), ('phone_holder_type', 'phone_holder_type'), ('keycaps_color', 'keycaps_color'), ('switch_color', 'switch_color'), ('spur_color', 'spur_color'), ('sprocket_color', 'sprocket_color'), ('screw_color', 'screw_color'), ('insert', 'insert'), ('keyboard_thickness', 'keyboard_thickness'), ('laptop_thickness', 'laptop_thickness'), ('drawer_size', 'drawer_size'), ('him_color', 'him_color'), ('she_color', 'she_color'), ('headphone_band_width', 'headphone_band_width')], max_length=100),
        ),
    ]
