# Generated by Django 4.2.7 on 2023-11-29 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_productvideo_video_and_more'),
        ('store', '0016_auto_20231125_1645'),
    ]

    operations = [
    ]
