# Generated by Django 4.2.7 on 2023-11-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_merge_20231129_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size'), ('pack', 'pack'), ('switchtype', 'switchtype'), ('mounting_option', 'mounting_option'), ('individual_color', 'individual_color'), ('shape', 'shape'), ('batteries_type', 'batteries_type'), ('set', 'set'), ('shelf_size', 'shelf_size'), ('container_type', 'container_type'), ('holder_size', 'holder_size'), ('first_color', 'first_color'), ('second_color', 'secondary_color'), ('third_color', 'third_color'), ('fourth_color', 'fourth_color'), ('type_placement', 'type_placement'), ('cage_color', 'cage_color'), ('seat_color', 'seat_color'), ('stand_type', 'stand_type'), ('phone_holder_type', 'phone_holder_type'), ('keycaps_color', 'keycaps_color'), ('switch_color', 'switch_color'), ('spur_color', 'spur_color'), ('sprocket_color', 'sprocket_color'), ('screw_color', 'screw_color'), ('insert', 'insert'), ('keyboard_thickness', 'keyboard_thickness'), ('laptop_thickness', 'laptop_thickness'), ('drawer_size', 'drawer_size'), ('him_color', 'him_color'), ('she_color', 'she_color'), ('option1', 'option1'), ('option2', 'option2'), ('option3', 'option3'), ('option4', 'option4'), ('option5', 'option5'), ('option6', 'option6'), ('option7', 'option7'), ('option8', 'option8'), ('option9', 'option9'), ('option10', 'option10')], max_length=100),
        ),
    ]
