# Generated by Django 3.1 on 2023-11-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default=11, max_length=255),
            preserve_default=False,
        ),
    ]
