# Generated by Django 3.1 on 2023-11-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contact_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='ticket_number',
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
